core/urls.py
from django.urls import path
from .views import views_donor, views_recyclingcenter


urlpatterns = [
    path('donor/', views_donor.userpage, name="userpage_donor"),
    path('donor/login/', views_donor.login_donor, name="login_donor"),
    path('donor/register/', views_donor.register_donor, name="register_donor"),
    path('donor/logout/', views_donor.logout_donor, name='logout_donor'),
    path('donor/about/', views_donor.about_donor, name='about_donor'),
    path('donor/search_rc/', views_donor.search_rc, name='search_rc'),
    path('donor/attendance/<id>/', views_donor.attendance, name='attendance'),
    path('donor/notifications_donor/', views_donor.notifications_donor, name='notifications_donor'),
    path('donor/receipt/<id>/', views_donor.receipt, name='receipt'),
    path('donor/confirm_donation/<id>', views_donor.confirm_donation, name='confirm_donation'),

    path('recyclingcenter/', views_recyclingcenter.userpage, name="userpage_recyclingcenter"),
    path('recyclingcenter/login/', views_recyclingcenter.login_recyclingCenter, name="login_recyclingcenter"),
    path('recyclingcenter/register/', views_recyclingcenter.register_recyclingCenter, name="registern_recyclingcenter"),
    path('recyclingcenter/logout/', views_recyclingcenter.logout_recyclingCenter, name="logout_recyclingCenter"),
    path('recyclingcenter/notifications/', views_recyclingcenter.notifications, name='notifications'),
    path('recyclingcenter/att_confirmation/<id>/', views_recyclingcenter.attending_confirmation, name='att_confirmation'),
    path('recyclingcenter/schedule/', views_recyclingcenter.schedule, name='schedule'),

    path('recyclingcenter/search/', views_recyclingcenter.search_donor, name="search_donor"),
    path('recyclingcenter/donation/<id>/', views_recyclingcenter.register_donation, name="register_donation"),
    
]

sdmr/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField
from django.db.models.fields.related import ForeignKey, OneToOneField

# Create your models here.

class Profile(AbstractUser):
    PROFILE_TYPE_CHOICES = [
        ("D", "Doador"),
        ("P", "Ponto de Coleta")
    ]
    email = models.EmailField(unique=True, 
            error_messages={'unique': "Já existe um usuário com este email", 'required': 'Por favor dgite um email'})
    profile_type = models.CharField(max_length=1, choices=PROFILE_TYPE_CHOICES)
    phone = models.CharField(max_length=11)
    about = models.TextField(max_length=300)
    img_profile = models.ImageField(upload_to='img_profile', null=True, blank=True)


class Donnor(Profile): # Donor
    cpf = models.CharField(max_length=11, unique=True, error_messages={'unique': "Já existe outro usuário com esse CPF"})
    ranking_points = models.PositiveIntegerField(default=0)
    general_points = models.PositiveIntegerField(default=0)


class Place(models.Model): # Address
    parent_company = models.CharField(max_length=100, verbose_name="Sede")
    place_name = models.CharField(max_length=100, verbose_name="Logradouro")
    number = models.CharField(max_length=10, verbose_name="Número")
    district = models.CharField(max_length=100, verbose_name="Bairro")
    city = models.CharField(max_length=100, verbose_name="Cidade")
    state = models.CharField(max_length=100, verbose_name="Estado")
    complement = models.CharField(max_length=200, null=True, blank=True, verbose_name="Complemento")


class RecyclingCenter(Profile):
    cnpj = models.CharField(max_length=14, unique=True, error_messages={'unique': 'Já existe outro usuário com esse CNPJ'})
    place = models.OneToOneField(Place, on_delete=CASCADE, null=True, blank=True)
    

class Attending(models.Model):
    STATUS_ATTENING_CHOICES = [
        ('CA', 'Confirmado atendimento'),
        ('AG', 'Aguardando confirmação'),
        ('CC', 'Cancelado'),
        ('AD', 'Aguardando confirmação de Doação'),
        ('CD', 'Concluído')
    ]
    requester = ForeignKey(Donnor, on_delete=CASCADE)
    recipient = ForeignKey(RecyclingCenter, on_delete=CASCADE)
    place = models.CharField(max_length=100)
    #address = models.ForeignKey(Address,) instead
    date_attending = models.DateTimeField()
    #date_attending = models.DateField() #instead
    #time_attending = models.TimeField() #instead
    obs = models.TextField(max_length=500)
    status_attending = models.CharField(max_length=2, choices=STATUS_ATTENING_CHOICES)
    #date_modification = models.DateTimeField(null=True, blank=True) 
    #date_joined = models.DateTimeField(auto_now_add=True)

    confirmed = models.BooleanField(default=None, null=True, blank=True)
    return_recipient = models.TextField(max_length=300)
    points_attending = models.TextField(default=0)
    #type_attending = models.CharField(max_length=2) # choices=(Avulso, Marcado)


class Messages(models.Model):
    user = models.ForeignKey(Profile, on_delete=CASCADE)
    attending = models.ForeignKey(Attending, on_delete=CASCADE)
    message = models.TextField()
    date_joined = models.DateTimeField(auto_now_add=True)


class Donation(models.Model):
    attending = OneToOneField(Attending, on_delete=CASCADE, null=True, blank=True)
    donor_id = models.ForeignKey(Donnor, on_delete=CASCADE)
    recyclingCenter_id = models.ForeignKey(RecyclingCenter, on_delete=CASCADE)
    description = models.TextField(max_length=300, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(null=True, blank=True)
    confirmed = models.BooleanField(default=None, null=True, blank=True)
    added_points = models.PositiveIntegerField(default=0) # null=True, blank=True


class RecyclabelMaterial(models.Model): # Material
    donation_id = models.ForeignKey(Donation, on_delete=CASCADE)
    material_name = models.CharField(max_length=100, null=False, blank=False)
    quatity = models.PositiveIntegerField(null=False, blank=False)
    #kg = models.DecimalField() # instead
    #points = models.FloatField()
    #type_material = CharField()

core/forms.py
from django import forms
from .models import Attending, Donation, Donnor, Place, Profile, RecyclabelMaterial, RecyclingCenter
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    user = forms.CharField(label="Usuário:", widget=forms.TextInput(attrs={'placeholder': 'Digite seu usuario'}))
    password = forms.CharField(label="Senha", widget=forms.PasswordInput(attrs={'placeholder': "Digite sua senha"}))


class RegisterDonorForm(UserCreationForm):
    first_name = forms.CharField(label="Nome")
    last_name = forms.CharField(label='Sobrenome')
    email = forms.EmailField(label='Email')
    phone = forms.CharField(label='Telefone')
    profile_type = forms.ChoiceField(choices=Profile.PROFILE_TYPE_CHOICES)
    cpf = forms.CharField(label='CPF', max_length=11)

    class Meta:
        model = Donnor
        fields = ['first_name', 'last_name','email', 'profile_type', 'cpf', 'username', 'password1', 'password2']


class RegisterRecyclingForm(UserCreationForm):
    first_name = forms.CharField(label="Razão Social")
    last_name = forms.CharField(label='Nome Fantasia')
    email = forms.EmailField(label='Email')
    profile_type = forms.ChoiceField(choices=Profile.PROFILE_TYPE_CHOICES)
    cnpj = forms.CharField(label='CNPJ', max_length=14)

    class Meta:
        model = RecyclingCenter
        fields = ['first_name', 'last_name', 'email', 'profile_type', 'cnpj', 'username', 'password1', 'password2']


class RegisterPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'


class RegisterDonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = '__all__'


class RegisterMaterialForm(forms.ModelForm):
    class Meta:
        model = RecyclabelMaterial
        fields = '__all__'
        widgets = {
            'material_name': forms.TextInput(attrs={'required':'',  'pattern':"[A-Za-z0-9]{1,100}"}),
            'quatity': forms.NumberInput(attrs={'onclick': 'calculator();', 'required':'','pattern':'[^0-9]\d+'}), 
        }


class SearchDonorForm(forms.Form):
    search = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Digite ID, nome ou sobrenome de alguém...'}))


class SearchRecyclingCenterForm(forms.Form):
    search = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Pesquise por um ponto de coleta...'}))


class AttendanceForm(forms.ModelForm):
    #place = forms.CharField(max_length=200)
    class Meta:
        model = Attending
        fields = '__all__'
        widgets = {
            'place': forms.TextInput(attrs={'readonly': ''}),
            
        }
        

core/views/views_donor.py
from core.models import Attending, Profile, Donation, RecyclabelMaterial
from django.shortcuts import redirect, render
from ..forms import AttendanceForm, LoginForm, RegisterDonationForm, RegisterDonorForm, SearchRecyclingCenterForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib import messages
from django.db.models.query_utils import Q

# Create your views here.
def user_type(login_url=None):
    return user_passes_test(lambda u: u.profile_type == 'D', login_url=login_url)

def register_donor(request):
    if request.POST:

        post = request.POST.copy()
        post['profile_type'] = Profile.PROFILE_TYPE_CHOICES[0][0]
        post['username'] = post['first_name'].lower() + post['last_name'].lower() + str(7)
        request.POST = post

        register_form = RegisterDonorForm(request.POST)
        
        if register_form.is_valid():
            register_form.save()
            return redirect('login_donor')
        else:
            messages.info(request, 'Não deu certo')
            return redirect('register_donor')
            #return HttpResponse("<h1>Não deu certo</h1>")
    register_form = RegisterDonorForm()
    content = {
        'register_form': register_form
    }
    return render(request, 'profile/donor/register.html', content)


def login_donor(request):
    if request.POST:
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['user'], password=cd['password'])
            if user is not None and user.profile_type == 'D':
                login(request, user)
                return redirect('userpage_donor')
            else:
                messages.info(request, 'Não autorizado')
                return redirect('login_donor')
    login_form = LoginForm()
    content = {
        'login_form': login_form
    }
    return render(request, 'profile/donor/login.html', content)


def logout_donor(request):
    logout(request)
    return redirect('login_donor')


@login_required(login_url='login_donor')
@user_type(login_url="login_donor")
def userpage(request):
    return render(request, 'profile/donor/home.html')


@login_required(login_url='login_donor')
@user_type(login_url="login_donor")
def about_donor(request):
    return render(request, 'profile/donor/about.html')


def search_rc(request):
    content_search = None
    if request.POST:
        if len(request.POST['search']) >= 3:
            # Quando id informado tiver 0's à esquerda
            search_id_str = request.POST.copy()
            while True:
                if search_id_str['search'][0] == '0':
                    search_id_str['search'] = search_id_str['search'].replace(search_id_str['search'][0], '')
                else:
                    break
            request.POST = search_id_str
            
            try:
                search_id = request.POST['search']
            except ValueError:
                pass
            search = Q(
                Q(
                    Q(id__contains=search_id) | 
                    Q(first_name__contains=request.POST['search']) | 
                    Q(last_name__contains=request.POST['search'])) & 
                Q(profile_type__exact='P'))

            content_search = Profile.objects.filter(search)
        else:
            messages.info(request, 'Digite no mínimo 3 caracteres')

    search_form = SearchRecyclingCenterForm()
    content = {
        'search_form': search_form,
        'content_search': content_search
    }
    return render(request, 'profile/donor/search_rc.html', content)


def attendance(request, id):
    rc = Profile.objects.get(id=id)
    
    attendance_form = AttendanceForm()

    if request.POST:
        post = request.POST.copy()
        post['requester'] = request.user
        post['recipient'] = rc
        post['place'] = 'Rua X nº Y - Bairro M, Fortaleza, CE'
        post['status_attending'] = Attending.STATUS_ATTENING_CHOICES[1][0]
        post['confirmed'] = None
        post['return_recipient'] = 'add coment'
        post['points_attending'] = 0
        request.POST = post

        attendance_form = AttendanceForm(request.POST)

        is_register_form = False
        print(attendance_form.is_valid())
        if attendance_form.is_valid():
            attendance_form.save()
            return redirect('search_rc')

    content ={
        'attendance': attendance_form,
        'rc': rc
    }
    return render(request, 'profile/donor/attendance.html', content)


def notifications_donor(request):
    query = Q(
        Q(requester=request.user.id) &

        Q(
            Q(status_attending__exact='CA')| 
            Q(status_attending__exact='CC')|
            Q(status_attending__exact='AD')
            
        )&
        Q(
            Q(confirmed=True)|
            Q(confirmed=False)
        )
    )

    attendings = Attending.objects.filter(query).order_by('-id')
    content = {
        'attendings': attendings
    }
    return render(request, 'profile/donor/notifications.html', content)


def receipt(request, id):
    receipt = Attending.objects.get(id=id)
    content = {
        'receipt': receipt
    }
    return render(request, 'profile/donor/receipt.html', content)


def confirm_donation(request, id):
    selected_attending = Attending.objects.get(id=id)
    selected_donation = Donation.objects.get(attending=selected_attending.id)
    materials = RecyclabelMaterial.objects.filter(donation_id=selected_donation.id)

    donation_form = RegisterDonationForm(request.POST or None, instance=selected_donation)
    print(donation_form)

    if request.POST:
        
        print(request.POST['confirmed'])
        if request.POST['confirmed'] == 'true':
            selected_donation.confirmed = True
            selected_attending.status_attending = Attending.STATUS_ATTENING_CHOICES[4][0]
            

        elif request.POST['confirmed'] == 'false':
            selected_donation.confirmed = False
            selected_attending.status_attending = Attending.STATUS_ATTENING_CHOICES[2][0]

        selected_donation.save()
        selected_attending.save()
        return redirect('search_rc')
    
    content = {
        'donation_form': donation_form,
        'materials': materials,
        'attending': selected_attending,
        'description': selected_donation.description
    }
    return render(request, 'profile/donor/confirm_donation.html', content)

core/templates/profile/donor/about.html
{% extends 'profile/donor/base/base_logged.html' %}

{% block title %}.:Página de usuário{% endblock %}

{% block content %}
<style>

</style>
<div class="col-md-10 ps-5 pe-5">
    <h1 class="text-end">Sobre mim</h1>
    <hr>
    <h3>Nome</h3>
    <p>{{ request.user.donnor.first_name}} {{ request.user.donnor.last_name}}</p>
    
    <h3>CPF</h3>
    <p>{{ request.user.donnor.cpf }}</p>

    <h3>Telefone</h3>
    <p>{{ request.user.phone }}</p>
    
    
</div>
</div>
{% endblock %}

core/templates/profile/donor/attendance.html
{% extends 'profile/donor/base/base_logged.html' %}

{% load filters %}

{% block title %}.:Página de usuário{% endblock %}

{% block content %}

<div class="col-md-10 ps-5 pe-5 mb-3">
    <h1 class="text-end">Atendimento</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <div id="shadow" class="card w-75 mx-auto shadow text-secondary">
            <div class="card-body border m-3 row">

                <div class="col-md-12">
                    <h2 class="">Dados do Ponto</h2>
                    <hr class="bg-secondary">
                </div>
                
                <div class="col-md-6">
                    <label class="h5">Código ID:</label>
                    {{ rc.id }}
                </div>

                <div class="col-md-6">
                    <label class="h5">Nome do local:</label>
                    {{ rc.first_name }}
                </div>

                <div class="col-md-6">
                    <label class="h5">Telefone:</label>
                    {% if rc.phone == '' %}
                    00 00000-0000
                    {{else}}
                    {{ rc.phone }}
                    {% endif %}
                </div>

                <div class="col-md-6">
                    <label class="h5">Email:</label>
                    {{ rc.email }}
                </div>

            </div>

            <div class="card-body row border m-3">
                <div class="col-md-12">
                    <h2>Dados de atendimento</h2>
                    <hr class="bg-secondary">
                    <label>Local:</label>
                    {{ attendance.place|f_class:'form-control' }}
                    {{ attendance.place.errors }}

                    <label>Horário:</label>
                    {{ attendance.date_attending|f_class:'form-control' }}
                    {{ attendance.date_attending.errors }}

                    <label class="mt-5">Comentário:</label>
                    {{ attendance.obs|f_class:'form-control'}}
                    {{ attendance.obs.errors }}
                </div>
            </div>
        </div>
        <div class="card-body border-0 w-75 mx-auto d-flex justify-content-end p-0 pt-3 ">
            <a href="{% url 'search_rc' %}" class="btn btn-lg btn-outline-danger me-3">Cancelar</a>
            <button type="submit" class="btn btn-lg btn-success">Confirmar</button>
        </div>
    </form>
</div>

</div>
{% endblock %}

core/templates/profile/donor/confirm_donation.html
{% extends 'profile/donor/base/base_logged.html' %}

{% load bootstrap %}
{% load filters %}

{% block title %}.:Doação{% endblock %}

{% block content %}
<style>
    #shadow {
        box-shadow: 1px 1px 8px rgb(183, 204, 183);
    }
</style>

<div class="col-md-10  ps-5 pe-5 mb-3">
    <h1 class="text-end">Registrar Doação</h1>
    <hr>

    <form method="POST">
        {% csrf_token %}
        <div id="shadow" class="card w-75 mx-auto text-secondary">
            <!--Alterações-->
            <div class="card-body row border m-3">
                <div>
                    <h2>Dados do atendimento</h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <label class="h5">Codigo atendimento</label>
                    {{ attending.id }}
                </div>
                <div class="col-md-6">
                    <label class="h5">Local</label>
                    {{ attending.place }}
                </div>

                <div class="col-md-6">
                    <label class="h5">Data</label>
                    {{ attending.date_attending.date }}
                </div>

                <div class="col-md-6">
                    <label class="h5">Horário</label>
                    {{ attending.date_attending.time }}
                </div>
            </div>

            <div class="card-body row border m-3">
                <div class="col-md-12">
                    <h2 class="">Dados do doador</h2>
                    <hr>
                </div>

                <div class="col-md-6">
                    <label class="h5">Código ID:</label>
                    {{ attending.requester.id}}

                </div>
                <div class="col-md-6">
                    <label class="h5">Doador:</label>
                    {{attending.requester.first_name}} {{ attending.requester.last_name }}

                </div>

                <div class="col-md-6">
                    <label class="h5">Telefone:</label>
                    {% if attending.requester.phone == '' %}
                    00 00000-0000
                    {{else}}
                    {{ attending.requester.phone }}
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <label class="h5">Email:</label>
                    {{ attending.requester.email }}
                </div>
            </div>

            <div class="card-body row border m-3">
                <div class="col-md-12">
                    <h2>Materiais doados</h2>
                    <hr>
                </div>
                <div class="col-md-12">
                    <table class="table">
                        <thead style="background-color: rgb(175, 231, 197);">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nome</th>
                                <th scope="col">Quantidade</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for material in materials %}
                            <tr>
                                <th scope="row">#</th>
                                <td> {{ material.material_name }}</td>
                                <td>{{ material.quatity }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
                <div class="col-md-12 row">
                    <div class="col-md-3">
                        <label class="fw-bold h5">Obs. do Ponto:</label>
                    </div>
                    <div class="col-md-9 p-0">
                        {{ description }}
                    </div>
                </div>
            </div>
            <div class="card-body row border m-3">
                <div class="col-md-12 row">
                    <h2>Conformar Doação</h2>
                    <hr>
                    <div class="col-md-6 text-end">
                        <label class="fw-bold h5 mt-1 text-danger">Confirmar?</label>
                    </div>
                    <div class="col-md-6 d-flex justify-content-start">
                        {{ donation_form.confirmed|f_class:'form-control w-50' }}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body border-0 w-75 mx-auto d-flex justify-content-end p-0 pt-3">

            <!--a href="{% url 'search_donor' %}" class="btn btn-lg btn-outline-danger me-3">Recusar</a-->
            <button type="submit" class="btn btn-lg btn-success">Confirmar</button>

        </div>
    </form>
</div>

</div>
{% endblock %}

{% block scripts%}
<!--script>
    // Criar Forms
    function add_form() {
        var total_forms = document.querySelector('#id_recyclabelmaterial_set-TOTAL_FORMS');
        var new_form_value = parseInt(total_forms.value) - 1;

        // new fields for material
        var new_label_material_name = document.createElement('Material');
        new_label_material_name.innerHTML = 'Material';
        var new_input_material_name = document.querySelector('#id_recyclabelmaterial_set-0-material_name')
            .cloneNode(true);
        new_input_material_name.name = 'recyclabelmaterial_set-' + new_form_value + '-material_name';
        new_input_material_name.id = 'id_recyclabelmaterial_set-' + new_form_value + '-material_name';
        new_input_material_name.value = ''

        var new_label_quantity = document.createElement('Qtde');
        new_label_quantity.innerHTML = 'Qtde';
        var new_input_quantity = document.querySelector('#id_recyclabelmaterial_set-0-quatity')
            .cloneNode(true);
        new_input_quantity.name = 'recyclabelmaterial_set-' + new_form_value + '-quatity';
        new_input_quantity.id = 'id_recyclabelmaterial_set-' + new_form_value + '-quatity';
        new_input_quantity.value = ''

        document.querySelector('#col-md-6_form-' + new_form_value).appendChild(new_label_material_name);
        document.querySelector('#col-md-6_form-' + new_form_value).appendChild(new_input_material_name);

        document.querySelector('#col-md-2_form-' + new_form_value).appendChild(new_label_quantity);
        document.querySelector('#col-md-2_form-' + new_form_value).appendChild(new_input_quantity);


        var new_label_remove = document.createElement('INPUT');
        new_label_remove.innerHTML = 'Remover';
        new_label_remove.className = 'btn btn-danger';
        new_label_remove.type = 'button';
        new_label_remove.value = 'Remover';
        new_label_remove.id = 'id_recyclabelmaterial_set-' + new_form_value + '-button_remove';

        new_label_remove.setAttribute("onclick", "remove_form('" + new_form_value + "');")

        document.querySelector('#col-md-3_form-' + new_form_value).appendChild(new_label_remove);
        //document.querySelector('#form_add').appendChild(new_input_remove);

        //total_forms.value = parseInt(total_forms.value) + 1;

    }

    // Criar DIVs
    function add_tags() {
        var total_forms = document.querySelector('#id_recyclabelmaterial_set-TOTAL_FORMS');

        div_row = document.createElement("DIV");
        div_row.className = 'row';
        div_row.id = 'row_form-' + total_forms.value;
        document.querySelector('#form_add').appendChild(div_row);

        div_col_6 = document.createElement("DIV");
        div_col_6.className = 'col-md-6';
        div_col_6.id = 'col-md-6_form-' + total_forms.value;
        document.querySelector('#' + div_row.id).appendChild(div_col_6)

        div_col_2 = document.createElement("DIV");
        div_col_2.className = 'col-md-2';
        div_col_2.id = 'col-md-2_form-' + total_forms.value;
        document.querySelector('#' + div_row.id).appendChild(div_col_2);

        div_col_3 = document.createElement("DIV");
        div_col_3.className = 'mt-4 col-md-3';
        div_col_3.id = 'col-md-3_form-' + total_forms.value;
        document.querySelector('#' + div_row.id).appendChild(div_col_3);

        total_forms.value = parseInt(total_forms.value) + 1;

        this.add_form();
    }

    // Remover Forms
    function remove_form(id) {
        var total_forms = document.querySelector('#id_recyclabelmaterial_set-TOTAL_FORMS');
        /*
        input_0 = document.getElementById('id_recyclabelmaterial_set-'+id+'-material_name');
        input_0.parentNode.removeChild(input_0);

        input_1 = document.getElementById('id_recyclabelmaterial_set-'+id+'-quatity');
        input_1.parentNode.removeChild(input_1);

        input_2 = document.getElementById('id_recyclabelmaterial_set-'+id+'-button_remove');
        input_2.parentNode.removeChild(input_2);
        */
        console.log('id_recyclabelmaterial_set-'+id+'-material_name');
        console.log('id_recyclabelmaterial_set-'+id+'-quatity');
        console.log('id_recyclabelmaterial_set-'+id+'-button_remove');

        /*
        div_1 = document.getElementById('col-md-6_form-'+id);
        div_1.parentNode.removeChild(div_1)
        
        div_2 = document.getElementById('col-md-2_form-'+id);
        div_2.parentNode.removeChild(div_2)

        div_3 = document.getElementById('col-md-3_form-'+id);
        div_3.parentNode.removeChild(div_3)*/

        div_0 = document.getElementById('row_form-'+id);
        div_0.parentNode.removeChild(div_0)

        console.log('row_form-'+id);
        console.log('col-md-6_form-'+id);
        console.log('col-md-2_form-'+id);
        console.log('col-md-3_form-'+id);

        //total_forms.value = parseInt(total_forms.value) - 1;
    }

    function calculator(){
        calc_0 = document.getElementById('id_recyclabelmaterial_set-0-quatity');
        result = document.getElementById('calculate');
        result.value = (parseInt(calc_0.value) * 0.25) + ' pts';
        console.log(result.value);
    }
</script-->
{% endblock %}

core/templates/profile/donor/receipt.html
{% extends 'profile/donor/base/base_logged.html' %}

{% load filters %}

{% block title %}.:Página de usuário{% endblock %}

{% block content %}

<div class="col-md-10 ps-5 pe-5 mb-3">
    <h1 class="text-end">Comprovante</h1>
    <hr>
    <div id="shadow" class="card w-75 mx-auto shadow text-secondary">
        <div class="card-body">
            <div class="card card-header mx-auto m-2">
                <div class="row">
                    <div class="col-md-6">
                        <label class="fw-bold h5">Codigo Atendimento</label>
                        {{ receipt.id }}
                    </div>
                    <div class="col-md-6 text-danger fw-bold">
                        <label class="fw-bold h5">Local</label>
                        {{ receipt.place }}
                    </div>

                    <div class="col-md-6">
                        <label class="fw-bold h5">Data</label>
                        {{ receipt.date_attending.date }}
                    </div>
                    <div class="col-md-6">
                        <label class="fw-bold h5">Horário</label>
                        {{ receipt.date_attending.time }}
                    </div>

                    <!--Status de Atendimento-->
                    {% if receipt.status_attending == 'CC' %}
                    <div class="col-md-12 h4 text-center mt-2 fw-bold p-1" style="background-color: rgb(243, 203, 187);">
                        {{ receipt.get_status_attending_display }}
                    </div>
                    {% endif %}

                    {% if receipt.status_attending == 'CA' %}
                    <div class="col-md-12 h4 text-center mt-2 fw-bold p-1" style="background-color: rgb(212, 243, 187);">
                        {{ receipt.get_status_attending_display }}
                    </div>
                    {% endif %}

                    <div class="col-md-12 mt-2">
                        <label class="fw-bold h5">Retorno do Ponto de coleta:</label><br>
                        {{ receipt.return_recipient }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}